"""Migration 076: ``invoices.first_printed_at`` timestamp.

Records the moment an invoice's main PDF was first generated by a user.
This lets the UI bundle the customer-signable Core Return slip (UAT
1.7b) on the *first* print only, while subsequent prints stay invoice-
only unless the user explicitly clicks "Print Core Slip".

The column is nullable (``NULL`` = never printed). No backfill — older
invoices simply behave as already-printed when next opened (their core
slips remain reachable via the explicit toolbar button).
"""
from __future__ import annotations


def _has_column(conn, table: str, column: str) -> bool:
    try:
        rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
        for r in rows:
            name = r[1] if not hasattr(r, "keys") else r["name"]
            if str(name) == column:
                return True
        return False
    except Exception:
        try:
            row = conn.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_name = %s AND column_name = %s",
                (table, column),
            ).fetchone()
            return bool(row)
        except Exception:
            return False


def migrate(conn) -> None:
    if not _has_column(conn, "invoices", "first_printed_at"):
        try:
            conn.execute(
                "ALTER TABLE invoices ADD COLUMN first_printed_at TIMESTAMP"
            )
        except Exception:
            conn.execute(
                "ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "
                "first_printed_at TIMESTAMP"
            )
    conn.commit()
