"""Database module for JAKS Scraper inventory management.

Supports both SQLite (local) and PostgreSQL (cloud) backends.
Set DATABASE_URL environment variable to configure:
  - PostgreSQL: postgresql://user:pass@host:5432/dbname
  - SQLite: sqlite:///output/inventory.db (default)
"""

from .database import get_db, get_connection, get_database_url, is_postgresql
from .inventory import (
    DB_PATH,
    init_db,
    sync_product_to_db,
    sync_products_batch,
    create_product,
    search_by_part_number,
    get_product_by_sku,
    get_product_by_id,
    update_product,
    get_all_xrefs_for_product,
    index_product_images,
    get_db_stats,
    search_by_manufacturer,
    get_products_needing_pai,
    find_duplicate_parts,
    # Inventory operations
    adjust_product_quantity,
    get_inventory_transactions,
    get_low_stock_products,
    bulk_adjust_quantity,
    # Browse helpers
    get_all_manufacturers,
    get_all_engine_manufacturers,
    get_all_engine_models,
    get_all_categories,
    get_all_subcategories,
    get_subcategories_for_category,
    get_all_suppliers,
    list_products_by_manufacturer,
    list_products_by_category,
    browse_products,
    get_all_products,
    # Vendor management
    get_all_vendors,
    get_vendor,
    create_vendor,
    update_vendor,
    delete_vendor,
    get_vendor_avg_transit_days,
    get_vendor_stats,
    # Purchase order management
    generate_po_number,
    get_all_purchase_orders,
    get_purchase_order,
    create_purchase_order,
    add_po_line,
    add_or_merge_po_line,
    add_discount_line,
    find_open_purchase_orders_for_vendor,
    update_po_status,
    update_purchase_order,
    update_po_line,
    remove_po_line,
    receive_po_line,
    # Purchase receipts
    generate_receipt_number,
    list_receivable_pos,
    create_receipt_draft,
    get_receipt,
    list_receipts,
    save_receipt_draft,
    finalize_receipt,
    void_receipt,
    # Quote management
    generate_quote_number,
    get_all_quotes,
    get_quote,
    create_quote,
    add_quote_line,
    remove_quote_line,
    update_quote_line,
    set_or_replace_warranty_line,
    reorder_quote_lines,
    update_quote,
    convert_quote_to_invoice,
    convert_quote_to_so,
    create_po_from_so,
    # Quote comments
    get_quote_comments,
    add_quote_comment,
    # Customer management
    get_all_customers,
    get_customer,
    get_customer_by_email,
    create_customer,
    update_customer,
    delete_customer,
    search_customers,
    # Invoice management
    generate_invoice_number,
    get_all_invoices,
    get_invoice,
    get_invoice_by_number,
    create_invoice,
    add_invoice_line,
    remove_invoice_line,
    update_invoice_line_price,
    update_invoice_line_core_charge,
    update_invoice_status,
    update_invoice,
    finalize_invoice,
    revert_invoice_to_draft,
    record_payment,
    list_invoice_payments,
    get_invoice_payment_total,
    void_invoice_payment,
    get_customer_invoices,
    # Storage locations (Phase I)
    list_locations,
    get_location,
    get_location_by_code,
    create_location,
    update_location,
    delete_location,
    get_products_at_location,
    get_product_locations,
    assign_product_to_location,
    remove_product_from_location,
    get_location_utilization,
    search_locations,
    # Serial/Lot tracking (Phase I Part 2)
    list_serials,
    get_serial,
    get_serial_by_number,
    create_serial,
    update_serial,
    sell_serial,
    return_serial,
    delete_serial,
    get_available_serials,
    get_product_serial_count,
    search_serials,
    bulk_create_serials,
    # Core returns (Phase I Part 3)
    list_core_returns,
    get_core_return,
    create_core_return,
    update_core_return,
    receive_core,
    issue_core_credit,
    void_core_return,
    delete_core_return,
    get_pending_cores,
    get_core_returns_for_invoice,
    invoice_has_cores,
    mark_invoice_first_printed,
    get_core_returns_for_customer,
    get_core_summary,
    create_core_from_invoice_line,
    # Customer credits ledger (migration 069)
    list_customer_credits,
    get_open_credit_total,
    apply_credit_to_invoice,
    void_customer_credit,
    create_manual_customer_credit,
    refund_customer_credit,
    # Customer warranty certificates (migration 071)
    materialize_warranty_certificates,
    void_warranties_for_invoice,
    list_customer_warranties,
    get_customer_warranty,
    list_warranties_for_invoice,
    void_customer_warranty,
    record_warranty_claim,
    expire_due_warranties,
    # Vendor core returns (PO core charges)
    list_vendor_core_returns,
    get_vendor_core_return,
    get_vendor_core_credits_for_qbo,
    update_vendor_core_return,
    mark_vendor_core_shipped,
    mark_vendor_core_credited,
    write_off_vendor_core,
    void_vendor_core,
    delete_vendor_core_return,
    get_vendor_core_summary,
    # Inventory transfers (Phase I Part 4)
    generate_transfer_number,
    list_transfers,
    get_transfer,
    get_transfer_by_number,
    create_transfer,
    add_transfer_line,
    remove_transfer_line,
    get_transfer_lines,
    update_transfer_status,
    complete_transfer,
    cancel_transfer,
    delete_transfer,
    get_transfer_summary,
    # Min/Max Restock (Phase 2)
    get_restock_products,
    get_restock_summary,
    update_min_max,
    # Inventory Audit (Phase 2)
    create_audit,
    get_audit,
    list_audits,
    add_audit_line,
    update_audit_line,
    get_audit_lines,
    finalize_audit,
    cancel_audit,
    # QBO Export (Phase 2)
    get_unexported_invoices,
    get_unexported_bills,
    mark_invoices_exported,
    mark_pos_exported,
    mark_invoice_posted_manually,
    mark_invoice_unposted,
    mark_po_posted_manually,
    mark_po_unposted,
    is_invoice_locked,
    is_po_locked,
    log_qbo_export,
    get_export_history,
    get_paid_invoices_for_export,
    get_credit_memos_for_export,
    # Part Interchange (Phase 2)
    add_interchange,
    get_interchanges,
    delete_interchange,
    search_interchanges,
    bulk_import_interchanges,
    # ESN Engine Lookup (Phase 4)
    get_esn_cache,
    save_esn_cache,
    get_engine_compatibility,
    add_engine_compatibility,
    # Sales Orders
    generate_so_number,
    create_sales_order,
    get_sales_order,
    list_sales_orders,
    update_sales_order,
    add_so_line,
    get_so_lines,
    remove_so_line,
    update_so_line_price,
    convert_so_to_invoice,
    get_so_summary,
    get_backorder_lines,
    log_so_activity,
    get_so_activity,
    derive_so_line_status,
    derive_so_status,
    # Returns & Warranty (Phase 5)
    generate_rma_number,
    create_return,
    process_invoice_return,
    list_returns,
    update_return,
    get_return,
    refund_return_as_credit,
    set_rma_restocking_fee,
    # Price Tiers
    list_price_tiers,
    get_price_tier,
    create_price_tier,
    update_price_tier,
    delete_price_tier,
    set_customer_pricing,
    get_customer_price,
    get_customer_pricing_rules,
    delete_customer_pricing,
    get_product_map_price,
    set_product_map_price,
    record_lost_sale,
    list_lost_sales,
    get_lost_sale_summary,
    get_customer_product_history,
    add_product_fitment,
    list_product_fitments,
    delete_product_fitment,
    search_products_by_fitment,
    add_part_supersession,
    get_part_supersession_chain,
    find_current_replacement_product,
    list_part_supersessions_for_product,
    delete_part_supersession,
    allocate_landed_costs,
    get_landed_costs_for_po,
    # Tiered Pricing v2 (categories × bands × tier discounts)
    list_price_categories,
    get_price_category,
    get_default_price_category,
    create_price_category,
    update_price_category,
    delete_price_category,
    list_bands,
    set_bands,
    find_band_for_cost,
    list_customer_tiers,
    get_customer_tier,
    get_default_customer_tier,
    create_customer_tier,
    update_customer_tier,
    delete_customer_tier,
    get_tier_category_discount,
    set_tier_category_discount,
    get_tier_discount_grid,
    get_manufacturer_category,
    set_manufacturer_category,
    list_manufacturer_categories,
    get_vendor_category,
    set_vendor_category,
    list_vendor_categories,
    resolve_product_category,
    resolve_customer_tier,
    compute_price,
    # Vendor Returns (RGA)
    generate_rga_vr_number,
    create_vendor_return,
    list_vendor_returns,
    get_vendor_return,
    update_vendor_return,
    add_vendor_return_line,
    get_vendor_return_lines,
    remove_vendor_return_line,
    get_vendor_return_summary,
    # Vendor Core RGA (migration 107)
    list_eligible_vendor_cores_for_rga,
    attach_vendor_cores_to_rga,
    log_vendor_return_event,
    get_vendor_return_audit,
    transition_vendor_core_status,
    transition_rga_status,
    get_vendor_core_kpis,
    list_outstanding_vendor_obligations,
    delete_vendor_return,
    # Product workbench: quantity tiers
    get_product_qty_tiers,
    set_product_qty_tiers,
)

# Core Handling Overhaul (migration 108)
from .core_handling import (
    PRODUCT_CORE_TYPES,
    VENDOR_CORE_HANDLING_OPTIONS,
    BEHAVIOR_VALUES,
    CONDITIONAL_EXCHANGE_NOTE,
    REFUNDABLE_CORE_FOOTER,
    VCO_STATUSES,
    resolve_core_behavior,
    get_core_amount_for_product,
    create_vendor_core_obligation,
    list_vendor_core_obligations,
    update_vendor_core_obligation,
    delete_vendor_core_obligations_for_po_line,
    get_outstanding_vendor_core_amount,
)

from .inventory import (
    # Kits / Assemblies
    list_kits,
    get_kit,
    create_kit,
    update_kit,
    delete_kit,
    add_kit_component,
    remove_kit_component,
    get_kit_components,
    get_kit_availability,
    explode_kit_to_lines,
    # Shipments / Deliveries
    create_shipment,
    list_shipments,
    get_shipment,
    update_shipment,
    confirm_delivery,
    get_delivery_summary,
    get_eta_board,
    # Supersessions
    add_supersession,
    get_supersession_chain,
    get_supersessions_for_sku,
    delete_supersession,
    search_supersessions,
    # Margin Analysis
    get_product_margins,
    get_customer_margins,
    get_margin_summary,
    # Reorder Suggestions
    get_reorder_suggestions,
    # Customer Purchase History
    get_customer_purchase_history,
    get_customer_frequently_ordered,
    # Customer Employees
    get_customer_employees,
    add_customer_employee,
    update_customer_employee,
    delete_customer_employee,
    # Credit Agreements
    get_credit_agreement,
    save_credit_agreement,
    # Customer Analytics
    get_customer_aging,
    get_customer_spending_summary,
    get_customer_outstanding_cores,
    get_customer_grid_data,
    get_customer_overdue_cores,
    # SKU Prefix Management
    list_sku_prefixes,
    get_sku_prefix,
    create_sku_prefix,
    delete_sku_prefix,
    generate_sku,
    get_next_sku_preview,
    update_sku_prefix,
    generate_next_sku,
    get_sku_prefix_for_vendor,
    get_sku_prefixes,
    # Duplicate Detection
    find_similar_products,
    # Sales Velocity & Auto Min/Max
    get_sales_velocity,
    auto_calculate_min_max,
    get_velocity_report,
    # Bulk Product Import
    bulk_import_products,
    get_import_history,
    # P0.2 — inventory reservation audit
    reconcile_qty_reserved,
    # Stock-state read helpers (UI)
    compute_available,
    get_open_reservations,
    get_stock_state,
    # CRM Customer Activities
    add_customer_activity,
    get_customer_activities,
    get_all_activities,
    get_upcoming_followups,
    complete_activity,
    delete_activity,
    # Daily Route Planner
    get_or_create_daily_route,
    get_daily_route,
    add_route_stop,
    update_route_stop,
    complete_route_stop,
    skip_route_stop,
    delete_route_stop,
    reorder_route_stops,
    complete_daily_route,
    auto_populate_route,
    get_route_directions_url,
    get_stop_directions_url,
    # Customer 360 View
    get_customer_360,
    update_customer_coords,
    # Aging AR
    get_aging_report,
    # App Settings
    get_setting,
    set_setting,
    get_all_settings,
    # Sales Tax Rates
    list_tax_rates,
    upsert_tax_rate,
    delete_tax_rate,
    get_tax_rate_for_address,
    resolve_tax_rate,
    get_qbo_tax_code_for_rate,
    # Data Reset & QBO CSV Import
    reset_all_data,
    import_customers_from_csv,
    import_vendors_from_csv,
    import_products_from_csv,
    import_invoices_from_csv,
    import_invoice_lines_from_csv,
    # Scraper functions
    create_scrape_run,
    update_scrape_run,
    get_scrape_runs,
    get_last_scrape_run,
    save_scraped_xref,
    get_pending_scraped_xrefs,
    accept_scraped_xref,
    reject_scraped_xref,
    get_scraped_xref_counts,
    save_competitor_price,
    get_pending_competitor_prices,
    accept_competitor_price,
    reject_competitor_price,
    get_competitor_price_counts,
    get_latest_competitor_prices,
    get_scrape_dates_for_product,
    get_product_images,
    add_product_image,
    delete_product_image,
    get_product_sales_stats,
    delete_product,
    get_customers_who_bought,
    get_last_sold_date,
    get_sales_summary_batch,
    get_on_order_qty_batch,
    get_recent_events,
    # Marketing Phase 2
    get_sms_templates,
    get_sms_template,
    create_sms_template,
    update_sms_template,
    delete_sms_template,
    get_saved_audiences,
    get_saved_audience,
    create_saved_audience,
    update_saved_audience,
    delete_saved_audience,
    create_campaign,
    get_campaigns,
    get_campaign,
    update_campaign,
    add_campaign_recipient,
    get_campaign_recipients,
    update_campaign_recipient,
    get_automation_rules,
    get_automation_rule,
    update_automation_rule,
    add_automation_log,
    get_automation_log,
    update_automation_log_status,
    filter_customers_by_criteria,
    get_customers_who_bought_product,
    get_stale_quotes,
    get_inactive_customers,
    get_customers_near_credit_limit,
    get_conversation_stats,
    # Suggested Sells
    add_suggested_sell,
    get_suggested_sells,
    delete_suggested_sell,
    update_suggested_sell,
    # Shipping Estimation
    estimate_shipping_cost,
    estimate_order_shipping,
    get_shipping_rates,
    update_shipping_rate,
)

from .migrate import apply_schema_updates
from .shopify_sync import (
    sync_from_shopify,
    push_product_to_shopify,
    push_all_pending_to_shopify,
    get_sync_status,
    mark_product_for_update,
)

__all__ = [
    # Database abstraction
    "get_db",
    "get_connection",
    "get_database_url",
    "is_postgresql",
    # Inventory functions
    "DB_PATH",
    "init_db",
    "sync_product_to_db",
    "sync_products_batch",
    "create_product",
    "search_by_part_number",
    "get_product_by_sku",
    "get_product_by_id",
    "update_product",
    "get_all_xrefs_for_product",
    "index_product_images",
    "get_db_stats",
    "search_by_manufacturer",
    "get_products_needing_pai",
    "find_duplicate_parts",
    # Inventory operations
    "adjust_product_quantity",
    "get_inventory_transactions",
    "get_low_stock_products",
    "bulk_adjust_quantity",
    # Browse helpers
    "get_all_manufacturers",
    "get_all_engine_manufacturers",
    "get_all_engine_models",
    "get_all_categories",
    "get_all_subcategories",
    "get_all_suppliers",
    "list_products_by_manufacturer",
    "list_products_by_category",
    "browse_products",
    "get_all_products",
    # Vendor management
    "get_all_vendors",
    "get_vendor",
    "create_vendor",
    "update_vendor",
    "delete_vendor",
    "get_vendor_avg_transit_days",
    "get_vendor_stats",
    # Purchase order management
    "generate_po_number",
    "get_all_purchase_orders",
    "get_purchase_order",
    "create_purchase_order",
    "add_po_line",
    "add_or_merge_po_line",
    "add_discount_line",
    "find_open_purchase_orders_for_vendor",
    "update_po_status",
    "update_purchase_order",
    "update_po_line",
    "remove_po_line",
    "receive_po_line",
    # Purchase receipts
    "generate_receipt_number",
    "list_receivable_pos",
    "create_receipt_draft",
    "get_receipt",
    "list_receipts",
    "save_receipt_draft",
    "finalize_receipt",
    "void_receipt",
    # Quote management
    "generate_quote_number",
    "get_all_quotes",
    "get_quote",
    "create_quote",
    "add_quote_line",
    "remove_quote_line",
    "update_quote_line",
    "set_or_replace_warranty_line",
    "update_quote",
    "convert_quote_to_invoice",
    # Customer management
    "get_all_customers",
    "get_customer",
    "get_customer_by_email",
    "create_customer",
    "update_customer",
    "delete_customer",
    "search_customers",
    # Invoice management
    "generate_invoice_number",
    "get_all_invoices",
    "get_invoice",
    "get_invoice_by_number",
    "create_invoice",
    "add_invoice_line",
    "remove_invoice_line",
    "update_invoice_line_price",
    "update_invoice_line_core_charge",
    "update_invoice_status",
    "update_invoice",
    "finalize_invoice",
    "revert_invoice_to_draft",
    "record_payment",
    "list_invoice_payments",
    "get_invoice_payment_total",
    "void_invoice_payment",
    "get_customer_invoices",
    # Storage locations (Phase I)
    "list_locations",
    "get_location",
    "get_location_by_code",
    "create_location",
    "update_location",
    "delete_location",
    "get_products_at_location",
    "get_product_locations",
    "assign_product_to_location",
    "remove_product_from_location",
    "get_location_utilization",
    "search_locations",
    # Serial/Lot tracking (Phase I Part 2)
    "list_serials",
    "get_serial",
    "get_serial_by_number",
    "create_serial",
    "update_serial",
    "sell_serial",
    "return_serial",
    "delete_serial",
    "get_available_serials",
    "get_product_serial_count",
    "search_serials",
    "bulk_create_serials",
    # Core returns (Phase I Part 3)
    "list_core_returns",
    "get_core_return",
    "create_core_return",
    "update_core_return",
    "receive_core",
    "issue_core_credit",
    "void_core_return",
    "delete_core_return",
    "get_pending_cores",
    "get_core_returns_for_invoice",
    "invoice_has_cores",
    "mark_invoice_first_printed",
    "get_core_returns_for_customer",
    "get_core_summary",
    "create_core_from_invoice_line",
    # Customer credits ledger (migration 069)
    "list_customer_credits",
    "get_open_credit_total",
    "apply_credit_to_invoice",
    "void_customer_credit",
    "create_manual_customer_credit",
    "refund_customer_credit",
    # Customer warranty certificates (migration 071)
    "materialize_warranty_certificates",
    "void_warranties_for_invoice",
    "list_customer_warranties",
    "get_customer_warranty",
    "list_warranties_for_invoice",
    "void_customer_warranty",
    "record_warranty_claim",
    "expire_due_warranties",
    # Vendor core returns
    "list_vendor_core_returns",
    "get_vendor_core_return",
    "get_vendor_core_credits_for_qbo",
    "update_vendor_core_return",
    "mark_vendor_core_shipped",
    "mark_vendor_core_credited",
    "write_off_vendor_core",
    "void_vendor_core",
    "delete_vendor_core_return",
    "get_vendor_core_summary",
    # Inventory transfers (Phase I Part 4)
    "generate_transfer_number",
    "list_transfers",
    "get_transfer",
    "get_transfer_by_number",
    "create_transfer",
    "add_transfer_line",
    "remove_transfer_line",
    "get_transfer_lines",
    "update_transfer_status",
    "complete_transfer",
    "cancel_transfer",
    "delete_transfer",
    "get_transfer_summary",
    # Min/Max Restock (Phase 2)
    "get_restock_products",
    "get_restock_summary",
    "update_min_max",
    # Inventory Audit (Phase 2)
    "create_audit",
    "get_audit",
    "list_audits",
    "add_audit_line",
    "update_audit_line",
    "get_audit_lines",
    "finalize_audit",
    "cancel_audit",
    # QBO Export (Phase 2)
    "get_unexported_invoices",
    "get_unexported_bills",
    "mark_invoices_exported",
    "mark_pos_exported",
    "mark_invoice_posted_manually",
    "mark_invoice_unposted",
    "mark_po_posted_manually",
    "mark_po_unposted",
    "is_invoice_locked",
    "is_po_locked",
    "log_qbo_export",
    "get_export_history",
    "get_paid_invoices_for_export",
    "get_credit_memos_for_export",
    # Part Interchange (Phase 2)
    "add_interchange",
    "get_interchanges",
    "delete_interchange",
    "search_interchanges",
    "bulk_import_interchanges",
    # ESN Engine Lookup (Phase 4)
    "get_esn_cache",
    "save_esn_cache",
    "get_engine_compatibility",
    "add_engine_compatibility",
    # Sales Orders
    "generate_so_number",
    "create_sales_order",
    "get_sales_order",
    "list_sales_orders",
    "update_sales_order",
    "add_so_line",
    "get_so_lines",
    "remove_so_line",
    "update_so_line_price",
    "convert_so_to_invoice",
    "get_so_summary",
    "get_backorder_lines",
    "log_so_activity",
    "get_so_activity",
    "derive_so_line_status",
    "derive_so_status",
    # Returns & Warranty (Phase 5)
    "generate_rma_number",
    "create_return",
    "process_invoice_return",
    "list_returns",
    "update_return",
    "get_return",
    "refund_return_as_credit",
    "set_rma_restocking_fee",
    # Price Tiers
    "list_price_tiers",
    "get_price_tier",
    "create_price_tier",
    "update_price_tier",
    "delete_price_tier",
    "set_customer_pricing",
    "get_customer_price",
    "get_customer_pricing_rules",
    "delete_customer_pricing",
    "get_product_map_price",
    "set_product_map_price",
    "record_lost_sale",
    "list_lost_sales",
    "get_lost_sale_summary",
    "get_customer_product_history",
    "add_product_fitment",
    "list_product_fitments",
    "delete_product_fitment",
    "search_products_by_fitment",
    "add_part_supersession",
    "get_part_supersession_chain",
    "find_current_replacement_product",
    "list_part_supersessions_for_product",
    "delete_part_supersession",
    "allocate_landed_costs",
    "get_landed_costs_for_po",
    # Tiered Pricing v2
    "list_price_categories",
    "get_price_category",
    "get_default_price_category",
    "create_price_category",
    "update_price_category",
    "delete_price_category",
    "list_bands",
    "set_bands",
    "find_band_for_cost",
    "list_customer_tiers",
    "get_customer_tier",
    "get_default_customer_tier",
    "create_customer_tier",
    "update_customer_tier",
    "delete_customer_tier",
    "get_tier_category_discount",
    "set_tier_category_discount",
    "get_tier_discount_grid",
    "get_manufacturer_category",
    "set_manufacturer_category",
    "list_manufacturer_categories",
    "get_vendor_category",
    "set_vendor_category",
    "list_vendor_categories",
    "resolve_product_category",
    "resolve_customer_tier",
    "compute_price",
    # Vendor Returns (RGA)
    "generate_rga_vr_number",
    "create_vendor_return",
    "list_vendor_returns",
    "get_vendor_return",
    "update_vendor_return",
    "add_vendor_return_line",
    "get_vendor_return_lines",
    "remove_vendor_return_line",
    "get_vendor_return_summary",
    # Vendor Core RGA (migration 107)
    "list_eligible_vendor_cores_for_rga",
    "attach_vendor_cores_to_rga",
    "log_vendor_return_event",
    "get_vendor_return_audit",
    "transition_vendor_core_status",
    "transition_rga_status",
    "get_vendor_core_kpis",
    "list_outstanding_vendor_obligations",
    "delete_vendor_return",
    # Product workbench: quantity tiers
    "get_product_qty_tiers",
    "set_product_qty_tiers",
    # Core Handling Overhaul (migration 108)
    "PRODUCT_CORE_TYPES",
    "VENDOR_CORE_HANDLING_OPTIONS",
    "BEHAVIOR_VALUES",
    "CONDITIONAL_EXCHANGE_NOTE",
    "REFUNDABLE_CORE_FOOTER",
    "VCO_STATUSES",
    "resolve_core_behavior",
    "get_core_amount_for_product",
    "create_vendor_core_obligation",
    "list_vendor_core_obligations",
    "update_vendor_core_obligation",
    "delete_vendor_core_obligations_for_po_line",
    "get_outstanding_vendor_core_amount",
    # Kits / Assemblies
    "list_kits",
    "get_kit",
    "create_kit",
    "update_kit",
    "delete_kit",
    "add_kit_component",
    "remove_kit_component",
    "get_kit_components",
    "get_kit_availability",
    "explode_kit_to_lines",
    # Shipments / Deliveries
    "create_shipment",
    "list_shipments",
    "get_shipment",
    "update_shipment",
    "confirm_delivery",
    "get_delivery_summary",
    "get_eta_board",
    # Supersessions
    "add_supersession",
    "get_supersession_chain",
    "get_supersessions_for_sku",
    "delete_supersession",
    "search_supersessions",
    # Margin Analysis
    "get_product_margins",
    "get_customer_margins",
    "get_margin_summary",
    # Reorder Suggestions
    "get_reorder_suggestions",
    # Customer Purchase History
    "get_customer_purchase_history",
    "get_customer_frequently_ordered",
    "get_customer_employees",
    "add_customer_employee",
    "update_customer_employee",
    "delete_customer_employee",
    "get_credit_agreement",
    "save_credit_agreement",
    "get_customer_aging",
    "get_customer_spending_summary",
    "get_customer_outstanding_cores",
    "get_customer_grid_data",
    "get_customer_overdue_cores",
    # SKU Prefix Management
    "list_sku_prefixes",
    "get_sku_prefix",
    "create_sku_prefix",
    "delete_sku_prefix",
    "generate_sku",
    "get_next_sku_preview",
    "update_sku_prefix",
    "generate_next_sku",
    "get_sku_prefix_for_vendor",
    "get_sku_prefixes",
    "find_similar_products",
    "get_sales_velocity",
    "auto_calculate_min_max",
    "get_velocity_report",
    # Bulk Product Import
    "bulk_import_products",
    "get_import_history",
    "reconcile_qty_reserved",
    "compute_available",
    "get_open_reservations",
    "get_stock_state",
    # CRM Customer Activities
    "add_customer_activity",
    "get_customer_activities",
    "get_all_activities",
    "get_upcoming_followups",
    "complete_activity",
    "delete_activity",
    # Daily Route Planner
    "get_or_create_daily_route",
    "get_daily_route",
    "add_route_stop",
    "update_route_stop",
    "complete_route_stop",
    "skip_route_stop",
    "delete_route_stop",
    "reorder_route_stops",
    "complete_daily_route",
    "auto_populate_route",
    "get_route_directions_url",
    "get_stop_directions_url",
    # Customer 360 View
    "get_customer_360",
    "update_customer_coords",
    # Aging AR
    "get_aging_report",
    # App Settings
    "get_setting",
    "set_setting",
    "get_all_settings",
    # Sales Tax Rates
    "list_tax_rates",
    "get_qbo_tax_code_for_rate",
    "upsert_tax_rate",
    "delete_tax_rate",
    "get_tax_rate_for_address",
    "resolve_tax_rate",
    # Data Reset & QBO CSV Import
    "reset_all_data",
    "import_customers_from_csv",
    "import_vendors_from_csv",
    "import_products_from_csv",
    "import_invoices_from_csv",
    "import_invoice_lines_from_csv",
    # Scraper functions
    "create_scrape_run",
    "update_scrape_run",
    "get_scrape_runs",
    "get_last_scrape_run",
    "save_scraped_xref",
    "get_pending_scraped_xrefs",
    "accept_scraped_xref",
    "reject_scraped_xref",
    "get_scraped_xref_counts",
    "save_competitor_price",
    "get_pending_competitor_prices",
    "accept_competitor_price",
    "reject_competitor_price",
    "get_competitor_price_counts",
    "get_latest_competitor_prices",
    "get_scrape_dates_for_product",
    "get_product_images",
    "add_product_image",
    "delete_product_image",
    "get_product_sales_stats",
    "delete_product",
    "get_customers_who_bought",
    "get_last_sold_date",
    "get_sales_summary_batch",
    "get_on_order_qty_batch",
    "get_recent_events",
    # Schema migrations (Phase J)
    "apply_schema_updates",
    # Shopify sync (Phase K)
    "sync_from_shopify",
    "push_product_to_shopify",
    "push_all_pending_to_shopify",
    "get_sync_status",
    "mark_product_for_update",
    # Marketing Phase 2
    "get_sms_templates",
    "get_sms_template",
    "create_sms_template",
    "update_sms_template",
    "delete_sms_template",
    "get_saved_audiences",
    "get_saved_audience",
    "create_saved_audience",
    "update_saved_audience",
    "delete_saved_audience",
    "create_campaign",
    "get_campaigns",
    "get_campaign",
    "update_campaign",
    "add_campaign_recipient",
    "get_campaign_recipients",
    "update_campaign_recipient",
    "get_automation_rules",
    "get_automation_rule",
    "update_automation_rule",
    "add_automation_log",
    "get_automation_log",
    "update_automation_log_status",
    "filter_customers_by_criteria",
    "get_customers_who_bought_product",
    "get_stale_quotes",
    "get_inactive_customers",
    "get_customers_near_credit_limit",
    "get_conversation_stats",
    # Shipping Estimation
    "estimate_shipping_cost",
    "estimate_order_shipping",
    "get_shipping_rates",
    "update_shipping_rate",
]
