from __future__ import annotations

from datetime import datetime
from sqlalchemy import String, Text, Integer, Boolean, ForeignKey, DateTime, Index, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base
from app.constants import ResearchStatus, ResearchUrgency, ResearchActivityType


class ResearchItem(Base):
    """
    Tracks unknown parts through the quote workflow until resolved.
    Number format: RI-2026-XXXX (generated by bump_counter).
    """
    __tablename__ = "research_items"
    __table_args__ = (
        Index("ix_research_items_status", "status"),
        Index("ix_research_items_customer_id", "customer_id"),
        Index("ix_research_items_assigned_user_id", "assigned_user_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    ri_number: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)

    # ── Source links ──────────────────────────────────────────────────────────
    customer_id: Mapped[int | None] = mapped_column(
        ForeignKey("customers.id"), nullable=True
    )
    quote_id: Mapped[int | None] = mapped_column(
        ForeignKey("quotes.id"), nullable=True
    )
    quote_line_id: Mapped[int | None] = mapped_column(
        ForeignKey("quote_lines.id"), nullable=True
    )

    # ── Assignment ────────────────────────────────────────────────────────────
    assigned_user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"), nullable=True
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default=ResearchStatus.OPEN
    )
    urgency: Mapped[str] = mapped_column(
        String(10), nullable=False, default=ResearchUrgency.NORMAL
    )

    # ── Part search context ───────────────────────────────────────────────────
    search_term: Mapped[str] = mapped_column(String(500), nullable=False, default="")
    oem_number: Mapped[str] = mapped_column(String(200), nullable=False, default="")
    vin: Mapped[str] = mapped_column(String(100), nullable=False, default="")
    esn: Mapped[str] = mapped_column(String(100), nullable=False, default="")
    engine_model: Mapped[str] = mapped_column(String(200), nullable=False, default="")
    notes: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # ── Follow-up ─────────────────────────────────────────────────────────────
    callback_due_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    # ── Resolution ────────────────────────────────────────────────────────────
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    resolved_product_id: Mapped[int | None] = mapped_column(
        ForeignKey("products.id"), nullable=True
    )
    resolution_notes: Mapped[str] = mapped_column(Text, nullable=False, default="")

    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now()
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    activity_log: Mapped[list[ResearchActivityLog]] = relationship(
        "ResearchActivityLog", back_populates="research_item", cascade="all, delete-orphan"
    )


class ResearchActivityLog(Base):
    """Activity log entries for a research item (calls, notes, status changes)."""
    __tablename__ = "research_activity_log"
    __table_args__ = (
        Index("ix_research_activity_log_research_item_id", "research_item_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    research_item_id: Mapped[int] = mapped_column(
        ForeignKey("research_items.id"), nullable=False
    )
    activity_type: Mapped[str] = mapped_column(
        String(30), nullable=False, default=ResearchActivityType.NOTE
    )
    notes: Mapped[str] = mapped_column(Text, nullable=False, default="")
    logged_by_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"), nullable=True
    )
    logged_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    research_item: Mapped[ResearchItem] = relationship(
        "ResearchItem", back_populates="activity_log"
    )
